Repository Riey/eraTHYMKR, pull requests merged in 2018-06, with the labels that each got.

#76 각종 버그 수정2
  ERB/CHARA/003 루미아/EX루미아/EVENT_K03.ERB
  ERB/CHARA/010 레밀리아/EVENT_K10.ERB
  ERB/CHARA/011 플랑드르/EVENT_K11.ERB
  ERB/CHARA/016 리리카/EVENT_K16.ERB
  ERB/CHARA/030 카구야/EVENT_K30.ERB
  ERB/CHARA/033 메디슨/EVENT_K33.ERB
  ERB/CHARA/064 코이시/EVENT_K64.ERB
  ERB/CHARA/068 토키코/EVENT_K68.erb
  ERB/COM/COMF4's/COMF432.ERB
  ERB/SYS/CONFIG/CONFIG2.ERB
  ERB/SYS/EVENT/EVENT_NINSHIN.ERB
  ERB/SYS/FUNCTIONS/SYSTEM_CHILD.ERB
  ERB/SYS/SHOP/SHOP.ERB
  ERB/SYS/TROPHY.ERB
Labels: 개선점, 구상, 버그, 시스템

#78 칭호에 등급 부여
  ERB/CHARA/072 코가사/EVENT_K171_A.ERB
  ERB/CHARA/072 코가사/EVENT_K72_A.ERB
  ERB/SYS/DAILY/DAILY_LIFE_SCRIPT.ERB
  ERB/SYS/EVENT/EVENT_COMMAND.ERB
  ERB/SYS/EVENT/EVENT_NIGHT0.ERB
  ERB/SYS/EVENT/EVENT_NIGHT1.ERB
  ERB/SYS/EVENT/EVENT_SUB.ERB
  ERB/SYS/FUNCTIONS/SYSTEM_CHILD.ERB
  ERB/SYS/FUNCTIONS/SYSTEM_NEWTERM.ERB
  ERB/SYS/INFO/HELP2.ERB
  ERB/SYS/INFO/HELP5.ERB
  ERB/SYS/PANCTION.ERB
  ERB/SYS/PRINT_STATE.ERB
  ERB/SYS/SHOP/SHOP.ERB
  ERB/SYS/SHOP/SHOP_ITEM.ERB
  ERB/SYS/SOURCE2.ERB
  etc/개발 자료/변수자료_eratohoYM자료.txt
Labels: 개선점, 버그, 시스템

#80 윤간버그 수정
  ERB/SYS/RINKAN.ERB
Labels: 버그, 시스템
