Repository Riey/eraTHYMKR, pull requests merged in 2018-05, with the labels that each got.

#59 각종 버그 수정 - 경험목록, 디버그 메뉴, 토리코모드
  ERB/SYS/FUNCTIONS/SYSTEM_DEBUG.ERB
  ERB/SYS/INFO/INFO0.ERB
  ERB/SYS/PRINT_STATE.ERB
  ERB/SYS/SHOP/SHOP.ERB
  ERB/TORIKO_MODE/TORIKOMODE.erb
  ERB/TORIKO_MODE/TORIKOMODE6.erb
Labels: 버그, 시스템

#62 범용 캐릭터, 딸, 템플릿에 사용되는 플래그 용도 정리
  CSV/GameBase.CSV
  ERB/COMMON_CHARA/COMF346_rev5.ERB
  ERB/COMMON_CHARA/EVENT_KX_ENDING.ERB
  ERB/COMMON_CHARA/EVENT_KX_EVENT.ERB
  ERB/COMMON_CHARA/EVENT_KX_LOVELY.ERB
  ERB/COMMON_CHARA/EVENT_KX_MAIN.ERB
  ERB/SYS/FUNCTIONS/SYSTEM_SUPPORT.ERB
  ERB/SYS/PANCTION_YM.ERB
  ERB/SYS/SHOP/SHOP_DRUGUSE2.ERB
  ERB/SYS/TRAIN_BEFORE.ERB
  etc/개발 자료/eratohoYM 국내 갱신판용 분할형 대사 템플릿/EVENT_KXX.ERB
  etc/개발 자료/eratohoYM 국내 갱신판용 분할형 대사 템플릿/EVENT_KXX_E0.ERB
  etc/개발 자료/변수교체 패치 예시 모음.txt
  etc/개발 자료/변수자료_eratohoYM자료.txt
  etc/개발 자료/플래그 리스트.erb
Labels: 개선점, 시스템

#65 여주인 임신 기능 구현
  ERB/COM/COMF0's/COMF025.ERB
  ERB/COM/COMF0's/COMF035.ERB
  ERB/COM/COMF3's/COMF307.ERB
  ERB/COM/COMF3's/COMF308.ERB
  ERB/COM/COMF3's/COMF323.ERB
  ERB/COM/COMF3's/COMF324.ERB
  ERB/COM/COMF3's/COMF325.ERB
  ERB/COM/COMF3's/COMF332.ERB
  ERB/COM/COMF3's/COMF333.ERB
  ERB/COM/COMF3's/COMF334.ERB
  ERB/COM/COMF3's/COMF338.ERB
  ERB/COM/COMF3's/COMF353.ERB
  ERB/COM/COMF3's/COMF382.ERB
  ERB/COM/COMF3's/COMF384.ERB
  ERB/COM/COMF6's/COMF651.ERB
  ERB/COM/COMF6's/COMF655.ERB
  ERB/COM/COMF6's/COMF656.ERB
  ERB/COMMON_CHARA/EVENT_KX_MAIN.ERB
  ERB/COMMON_CHARA/K149_FUNCTION.ERB
  ERB/MESSAGE/MESSAGE.ERB
  ERB/SYS/EVENT/EVENT_NINSHIN.ERB
  ERB/SYS/EVENT/EVENT_SHOOT.ERB
  ERB/SYS/FUNCTIONS/SYSTEM_CHILD.ERB
  ERB/SYS/FUNCTIONS/SYSTEM_SHOOT.ERB
  ERB/SYS/SOURCE0.ERB
Labels: 개선점, 버그, 시스템

#66 약품 계열 도움말 번역 개선, 실제 표시 되는 텍스트와 주석을 일치화.
  ERB/SYS/INFO/HELP4.ERB
Labels: 개선점, 시스템

#69 카게로 미번역분 번역완료
  ERB/CHARA/013 첸/EVENT_K13_C1.ERB
  ERB/CHARA/013 첸/EVENT_K13_C6.ERB
  ERB/CHARA/013 첸/EVENT_K13_E0.ERB
  ERB/CHARA/013 첸/EVENT_K13_T.ERB
  ERB/CHARA/100 미마/EVENT_K100.erb
  ERB/CHARA/222 카게로/EVENT_K222.ERB
  ERB/FEATURES/DESCRIPTION_ENABLE.ERH
  ERB/SYS/FUNCTIONS/SYSTEM_CONST.ERH
  ERB/SYS/FUNCTIONS/SYSTEM_VARIABLES.ERH
  README.md
Labels: 개선점, 구상
